language: objective-c
xcode_workspace: MSSPush.xcworkspace
xcode_scheme: MSSPushSpecs
xcode_sdk: iphonesimulator7.0

notifications:
    webhooks:
      - http://pulse.pivotallabs.com/projects/ebfc1f38-8ae7-4469-a9d4-c924880e1bda/status

before_install:
  - export LANG=en_US.UTF-8
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - pod install && cd $TRAVIS_BUILD_DIR

before_script:
  - brew update
  - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
